config/routes.rb
AlteredBeast::Application.routes.draw do
  get '/session' => "sessions#create", :as => 'open_id_complete'

  resources :sites, :moderatorships, :monitorship

  resources :forums do
    resources :topics do
      resources :posts
      resource :monitorship
    end
    resources :posts
  end

  resources :posts do
    get :search, :on => :collection
  end
  resources :users do
    member do
      put :suspend, :make_admin, :unsuspend
      get :settings
      delete :purge
    end
    resources :posts, :only => [:index] do
#      get :monitored, :on => :collection, :shallow => true
    end
  end
  match '/users/:user_id/monitored(.:format)' => 'posts#monitored', :as => 'monitored_posts'

  match '/activate/:activation_code' => 'users#activate', :activation_code => nil, :as => 'activate'
  match '/signup' => 'users#new', :as => 'signup'
  match '/settings' => 'users#settings', :as => 'settings'
  match '/login' => 'sessions#new', :as => 'login'
  match '/logout' => 'sessions#destroy', :as => 'logout'


  resource  :session
  
  
  root :to => redirect("/forums/the-red-army")
end

app/views/layouts/_head.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title><%=h @current_site && current_site.name || I18n.t('txt.beast_title', :default => 'The Red Army') %><%= " - #{h @page_title}" if @page_title %></title>
  <%= stylesheet_link_tag 'display' %>
  <%= stylesheet_link_tag 'captcha' %>
  <%= javascript_include_tag "prototype", "effects", "lowpro", 'rails', "application", :cache => "beast" %>
<% unless @feed_icons.blank? -%>
  <% @feed_icons.each do |feed| -%>
  <%= auto_discovery_link_tag :atom, feed[:url], :title => "Subscribe to '#{feed[:title]}'" %>
  <% end -%>
<% end -%>
  <link rel="search" type="application/opensearchdescription+xml" href="http://<%= request.host_with_port %>/open_search.xml" />
  <%= csrf_meta_tag %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-22952798-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body>

<div id="header">
  <ul id="nav">
	<% if logged_in? -%>
    <li><%= link_to I18n.t('txt.forums', :default => 'Forums'), root_path, :rel => 'home' %></li>
    <li><%= link_to I18n.t('txt.users', :default => 'Users'), users_path %></li>
    <li id="search">
      <%= form_tag posts_path, :method => 'get' do -%>
        <%= text_field_tag :q, params[:q], :size => 15, :id => :search_box %>
      <% end -%>
    </li>
    <li><%= link_to_function I18n.t('txt.search', :default => 'Search'), "#", :href => root_path, :id => 'search-link' %></li>
	<% end -%>
    <% if @current_site and logged_in? -%>
    <li class="login"><%=  link_to current_user.display_name, user_path(current_user) %></li>
    <li class="logout"><%= link_to I18n.t('txt.settings', :default => 'Settings'), settings_path %></li>
    <li class="logout"><%= link_to I18n.t('txt.logout', :default => 'Logout'), logout_path(:to => CGI.escape(request.fullpath)) %></li>
    <% else -%>
    <li><%= link_to I18n.t('txt.login', :default => 'Login'), login_path(:to => CGI.escape(request.fullpath)) %></li>
    <% end -%>
  </ul>
  <% name = (site = @current_site || Site.first) && site.name %>
  <h1><%= link_to name || I18n.t('txt.beast_title', :default => 'Altered Beast'), root_path %>
</div>

app/views/layouts/application.html.erb
<%= render :partial => "layouts/head" %>

<div id="container">
<div id="content">
  
<%= content_tag 'p', h(flash[:notice]), :class => 'notice' if flash[:notice] %>
<%= content_tag 'p', h(flash[:error]), :class => 'notice error' if flash[:error] %>

<%= yield %>
</div>

<div id="right">
  <%= yield :right %>
  <script type="text/javascript"><!--
  google_ad_client = "ca-pub-4095422081976458";
  /* redarmy.es sidebar */
  google_ad_slot = "4472158933";
  google_ad_width = 160;
  google_ad_height = 600;
  //-->
  </script>
  <script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
  </script>
</div>

<br style="clear:both;" />

</div>

<div id="footer">
  <p class="disclaim">
    <strong>
    <% if site = @current_site || Site.first %>
      <%= site.tagline %>
    <% end %>
    </strong>
  </p>
  <br style="clear:both;" />
</div>
</body>
</html>